steps:
  - label: "🤡 :hammer:"
    plugins:
      docker-compose#v2.5.1:
        run: tests
  - label: ":sparkles: lint"
    plugins:
      plugin-linter#v2.0.0:
        id: risepeopleinc/lambda-deploy
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.1:
        files: hooks/**
